# Minecraft Overworld
minecraft:acacia_savanna > biomesoplenty:redwood_forest
minecraft:badlands > biomesoplenty:redwood_forest
minecraft:bamboo_jungle > biomesoplenty:redwood_forest
minecraft:beach > biomesoplenty:redwood_forest
minecraft:birch_forest > biomesoplenty:redwood_forest
minecraft:cherry_grove > biomesoplenty:redwood_forest
minecraft:desert > biomesoplenty:redwood_forest
minecraft:dark_forest > biomesoplenty:redwood_forest
minecraft:eroded_badlands > biomesoplenty:redwood_forest
minecraft:flower_forest > biomesoplenty:redwood_forest
minecraft:frozen_ocean > biomesoplenty:redwood_forest
minecraft:forest > biomesoplenty:redwood_forest
minecraft:grove > biomesoplenty:redwood_forest
minecraft:ice_spikes > minecraft:frozen_peaks
minecraft:jagged_peaks > minecraft:frozen_peaks
minecraft:jungle > biomesoplenty:redwood_forest
minecraft:mangrove_swamp > biomesoplenty:redwood_forest
minecraft:meadow > biomesoplenty:redwood_forest
minecraft:mushroom_fields > biomesoplenty:redwood_forest
minecraft:old_growth_birch_forest > biomesoplenty:redwood_forest
minecraft:old_growth_pine_taiga > biomesoplenty:redwood_forest
minecraft:old_growth_spruce_taiga > biomesoplenty:redwood_forest
minecraft:plains > biomesoplenty:redwood_forest
minecraft:savanna > biomesoplenty:redwood_forest
minecraft:savanna_plateau > biomesoplenty:redwood_forest
minecraft:snowy_beach > biomesoplenty:redwood_forest
minecraft:snowy_plains > biomesoplenty:redwood_forest
minecraft:snowy_slopes > biomesoplenty:redwood_forest
minecraft:snowy_taiga > biomesoplenty:redwood_forest
minecraft:sparse_jungle > biomesoplenty:redwood_forest
minecraft:stony_peaks > minecraft:frozen_peaks
minecraft:stony_shore > terralith:yellowstone
minecraft:sunflower_plains > biomesoplenty:redwood_forest
minecraft:swamp > biomesoplenty:redwood_forest
minecraft:taiga > biomesoplenty:redwood_forest
minecraft:windswept_forest > biomesoplenty:redwood_forest
minecraft:windswept_gravelly_hills > biomesoplenty:redwood_forest
minecraft:windswept_hills > biomesoplenty:redwood_forest
minecraft:windswept_savanna > biomesoplenty:redwood_forest
minecraft:wooded_badlands > biomesoplenty:redwood_forest
minecraft:wooded_hills > biomesoplenty:redwood_forest
minecraft:wooded_mountains > biomesoplenty:redwood_forest

# Biomes O Plenty
biomesoplenty:alps > minecraft:frozen_peaks
biomesoplenty:aspen_glade > biomesoplenty:redwood_forest
biomesoplenty:auroral_garden > biomesoplenty:redwood_forest
biomesoplenty:bayou > biomesoplenty:redwood_forest
biomesoplenty:bog > terralith:yellowstone
biomesoplenty:cold_desert > biomesoplenty:redwood_forest
biomesoplenty:crag > biomesoplenty:redwood_forest
biomesoplenty:dead_forest > biomesoplenty:redwood_forest
biomesoplenty:dryland > biomesoplenty:redwood_forest
biomesoplenty:dune_beach > terralith:yellowstone
biomesoplenty:field > biomesoplenty:redwood_forest
biomesoplenty:floodplain > terralith:yellowstone
biomesoplenty:fungal_jungle > biomesoplenty:redwood_forest
biomesoplenty:forested_field > biomesoplenty:redwood_forest
biomesoplenty:fir_clearing > biomesoplenty:redwood_forest
biomesoplenty:grassland > biomesoplenty:redwood_forest
biomesoplenty:gravel_beach > terralith:yellowstone
biomesoplenty:highland > biomesoplenty:redwood_forest
biomesoplenty:jade_cliffs > biomesoplenty:redwood_forest
biomesoplenty:jacaranda_glade > biomesoplenty:redwood_forest
biomesoplenty:lavender_field > biomesoplenty:redwood_forest
biomesoplenty:lush_desert > biomesoplenty:redwood_forest
biomesoplenty:lush_savanna > biomesoplenty:redwood_forest
biomesoplenty:maple_woods > biomesoplenty:redwood_forest
biomesoplenty:snowy_maple_woods > biomesoplenty:redwood_forest
biomesoplenty:marsh > biomesoplenty:redwood_forest
biomesoplenty:mediterranean_forest > biomesoplenty:redwood_forest
biomesoplenty:muskeg > biomesoplenty:redwood_forest
biomesoplenty:mystic_grove > biomesoplenty:redwood_forest
biomesoplenty:old_growth_dead_forest > biomesoplenty:redwood_forest
biomesoplenty:old_growth_woodland > biomesoplenty:redwood_forest
biomesoplenty:orchard > biomesoplenty:redwood_forest
biomesoplenty:origin_valley > biomesoplenty:redwood_forest
biomesoplenty:overgrown_greens > biomesoplenty:redwood_forest
biomesoplenty:pasture > biomesoplenty:redwood_forest
biomesoplenty:prairie > biomesoplenty:redwood_forest
biomesoplenty:pumpkin_patch > biomesoplenty:redwood_forest
biomesoplenty:rainforest > biomesoplenty:redwood_forest
biomesoplenty:rocky_rainforest > biomesoplenty:redwood_forest
biomesoplenty:scrubland > biomesoplenty:redwood_forest
biomesoplenty:shrubland > biomesoplenty:redwood_forest
biomesoplenty:snowy_fir_clearing > biomesoplenty:redwood_forest
terralith:snowy_cherry_grove > biomesoplenty:redwood_forest
terralith:snowy_maple_forest > biomesoplenty:redwood_forest
terralith:maple_forest > biomesoplenty:redwood_forest
biomesoplenty:tropics > biomesoplenty:redwood_forest
biomesoplenty:tundra > biomesoplenty:redwood_forest
biomesoplenty:volcanic_plains > biomesoplenty:redwood_forest
biomesoplenty:volcano > biomesoplenty:redwood_forest
biomesoplenty:wasteland > biomesoplenty:redwood_forest
biomesoplenty:wetland > terralith:yellowstone
biomesoplenty:woodland > biomesoplenty:redwood_forest

# Terralith Snowy Biomes

# No Change
# terralith:wintry_forest
# terralith:snowy_shield
# terralith:siberian_grove

# Terralith Snowy Biomes
terralith:alpine_grove > terralith:snowy_shield
terralith:alpine_highlands > terralith:wintry_forest
terralith:birch_taiga > terralith:snowy_shield
terralith:cold_shrubland > terralith:siberian_grove
terralith:glacial_chasm > null
terralith:ice_marsh > terralith:snowy_shield
terralith:snowy_badlands > terralith:siberian_grove
terralith:wintry_lowlands > terralith:snowy_shield

# Terralith Remove
terralith:skylands_winter > null
terralith:skylands_spring > null
terralith:skylands_summer > null
terralith:skylands_autumn > null
terralith:alpha_isles > null
terralith:alpha_peaks > null

# Terralith

# Not Changing
# terralith:siberian_taiga
# terralith:frozen_cliffs
# biomesoplenty:redwood_forest
# terralith:granite_cliffs

# To Siberian Taiga
terralith:amethyst_rainforest > terralith:siberian_taiga
terralith:blooming_valley > terralith:siberian_taiga
terralith:blooming_valley_mountains > terralith:siberian_taiga
terralith:desert_dunes > terralith:siberian_taiga
terralith:fir_forest > biomesoplenty:redwood_forest
terralith:gravel_beach > terralith:yellowstone
terralith:gravel_desert > biomesoplenty:redwood_forest
terralith:jungle_mountains > null
terralith:maple_forest > biomesoplenty:redwood_forest
terralith:mirage_isles > biomesoplenty:redwood_forest
terralith:mushroom_forest > biomesoplenty:redwood_forest
terralith:oceanic_plains > biomesoplenty:redwood_forest
terralith:rainforest > biomesoplenty:redwood_forest
terralith:red_oasis > biomesoplenty:redwood_forest
terralith:spires > biomesoplenty:redwood_forest
# terralith:wooded_badlands > biomesoplenty:redwood_forest
# terralith:granite_ridge > biomesoplenty:redwood_forest
terralith:desert_oasis > biomesoplenty:redwood_forest
terralith:scarlet_mountains > biomesoplenty:redwood_forest
terralith:tropical_jungle > biomesoplenty:redwood_forest
terralith:temperate_highlands > biomesoplenty:redwood_forest
terralith:highlands > biomesoplenty:redwood_forest
terralith:blooming_plateau > biomesoplenty:redwood_forest
terralith:steppe > biomesoplenty:redwood_forest
terralith:orchid_swamp > terralith:siberian_taiga
terralith:yosemite_cliffs > terralith:siberian_taiga
terralith:amethyst_canyon > terralith:siberian_taiga


# To Forested Highland
# terralith:autumnal_valley > biomesoplenty:redwood_forest
terralith:brushland > biomesoplenty:redwood_forest
terralith:cloud_forest > biomesoplenty:redwood_forest
# terralith:cool_oak_forest > biomesoplenty:redwood_forest
terralith:fractured_savanna > null
terralith:haze_mountain > biomesoplenty:redwood_forest
terralith:lavender_valley > biomesoplenty:redwood_forest
terralith:lush_desert > biomesoplenty:redwood_forest
terralith:lush_valley > biomesoplenty:redwood_forest
# terralith:mixed_forest > biomesoplenty:redwood_forest
# terralith:monsoon_forest > biomesoplenty:redwood_forest
terralith:moonlight_valley > biomesoplenty:redwood_forest
terralith:white_cliffs > biomesoplenty:redwood_forest
# terralith:cedar_forest > biomesoplenty:redwood_forest
terralith:desert_spires > biomesoplenty:redwood_forest
terralith:sakura_grove > biomesoplenty:redwood_forest
terralith:yosemite_lowlands > biomesoplenty:redwood_forest
terralith:alpha_islands > biomesoplenty:redwood_forest
terralith:rocky_jungle > biomesoplenty:redwood_forest
# terralith:red_mountains > biomesoplenty:redwood_forest

# More Forest
terralith:arid_highlands > biomesoplenty:redwood_forest
terralith:bayou > biomesoplenty:redwood_forest
terralith:bryce_canyon > biomesoplenty:redwood_forest
terralith:caldera > biomesoplenty:redwood_forest
# terralith:crimson_gardens > biomesoplenty:redwood_forest
# terralith:crystalline_chasm > biomesoplenty:redwood_forest
# terralith:deep_ocean_ridge > biomesoplenty:redwood_forest
terralith:desert_canyon > biomesoplenty:redwood_forest
terralith:hot_shrubland > biomesoplenty:redwood_forest
# terralith:juniper_forest > biomesoplenty:redwood_forest
# terralith:mushroom_fields > biomesoplenty:redwood_forest
# terralith:oasis > terralith:yellowstone
# terralith:quartz_desert > biomesoplenty:redwood_forest
terralith:rocky_jungle > null
# terralith:red_mountains > biomesoplenty:redwood_forest
terralith:sandstone_valley > biomesoplenty:redwood_forest
terralith:windswept_spires > biomesoplenty:redwood_forest
terralith:shrubland > biomesoplenty:redwood_forest
terralith:moonlight_grove > biomesoplenty:redwood_forest
terralith:savanna_badlands > biomesoplenty:redwood_forest
terralith:white_mesa > biomesoplenty:redwood_forest
# terralith:eroded_badlands > biomesoplenty:redwood_forest
# terralith:wooded_badlands > biomesoplenty:redwood_forest

# Minecraft Caves
# minecraft:cave
# minecraft:dripstone_caves
# minecraft:lush_caves

# Terralith Caves
# terralith:amethyst_caves
# terralith:crystalline_caves
# terralith:deep_amethyst_caves
# terralith:echo_caves
# terralith:fungal_caves
# terralith:glimmering_caves
# terralith:mossy_caves
# terralith:quartz_caves
# terralith:stalactite_caves
# terralith:stone_chasms

