#List of the damage sources that will not cause an entity to bleed.
blacklist_bleed_sources = ["drown", "starve", "dryOut", "freeze", "fellOutOfWorld", "burn", "lava", "hotFloor", "onFire", "inFire"]

