#The maximum lifetime (20 ticks = 1 second) that a blood spatter will remain on screen for.
#Range: 0 ~ 10000
blood_spatter_lifetime = 600
#How loud the blood spatters are.
#Range: 0.0 ~ 1.0
blood_spatter_sound_volume = 0.75

