#This file stores configuration options for Iris, such as the currently active shaderpack
#Mon Jul 06 12:30:31 AEST 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=8
shaderPack=TheForest3 - High.zip
