#This file stores configuration options for Iris, such as the currently active shaderpack
#Wed Aug 12 20:36:43 AEST 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=8
shaderPack=Body Camera Shader - V1.6.1.zip
