#This file stores configuration options for Iris, such as the currently active shaderpack
#Mon Jul 06 14:34:45 AEST 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=8
shaderPack=Analog Shader - Lite.zip
enableShaders=false
