import { createHash } from 'node:crypto';
import { existsSync, mkdirSync, readdirSync, unlinkSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const outDir = 'config/hqm/default';
const setsDir = join(outDir, 'sets');

const wt = text => ({ text, isTranslationKey: false });
const stack = (id, Count = 1, tag = undefined) => tag ? { id, Count, tag } : { id, Count };
const itemPart = (id, required = 1, precision = undefined) => {
  const part = { item: stack(id), required };
  if (required === 1) delete part.required;
  if (precision) part.precision = precision;
  return part;
};
const manualTask = (title, body) => ({
  type: 'hardcorequesting:checkbox',
  description: wt(title),
  longDescription: wt(body)
});
const detectTask = (title, items, body = '') => ({
  type: 'hardcorequesting:detect',
  description: wt(title),
  longDescription: wt(body || 'Carry the listed supplies in your inventory.'),
  items: items.map(item => Array.isArray(item) ? itemPart(...item) : itemPart(item))
});
const craftTask = (title, items, body = '') => ({
  type: 'hardcorequesting:craft',
  description: wt(title),
  longDescription: wt(body || 'Craft the listed item after this quest is available.'),
  items: items.map(item => Array.isArray(item) ? itemPart(...item) : itemPart(item))
});
const consumeTask = (title, items, body = '') => ({
  type: 'hardcorequesting:consume',
  description: wt(title),
  longDescription: wt(body || 'Submit the listed supplies for the field cache.'),
  items: items.map(item => Array.isArray(item) ? itemPart(...item) : itemPart(item))
});
const killTask = (title, mob, kills, body = '') => ({
  type: 'hardcorequesting:kill',
  description: wt(title),
  longDescription: wt(body || 'Complete the listed clearing task after the route home is marked.'),
  mobs: [{ name: wt(title), mob, kills }]
});

const uuid = slug => {
  const h = createHash('md5').update(`the-forest-hqm:${slug}`).digest('hex');
  return `${h.slice(0, 8)}-${h.slice(8, 12)}-4${h.slice(13, 16)}-a${h.slice(17, 20)}-${h.slice(20, 32)}`;
};

const questIds = new Map();
const qid = slug => {
  if (!questIds.has(slug)) questIds.set(slug, uuid(slug));
  return questIds.get(slug);
};

function quest(slug, name, description, x, y, icon, tasks, rewards = [], prereq = []) {
  return {
    uuid: qid(slug),
    name: wt(name),
    description: wt(description),
    x,
    y,
    icon: stack(icon),
    tasks,
    prerequisites: prereq.map(qid),
    optionlinks: [],
    reward: rewards,
    rewardchoice: [],
    commandrewards: []
  };
}

const sets = [
  {
    file: 'first_clearing',
    name: 'The First Clearing',
    description: 'Start with ordinary field setup: confirm the kit, build a small shelter, mark the ground, and learn how the woods look after dark.',
    quests: [
      quest('clearing-wake', 'Field Log 00',
        'You arrived under old redwoods with a quest book, a survival kit, and a lot of work ahead. Treat the clearing as a survey site.',
        -140, 0, 'hardcorequesting:quest_book',
        [manualTask('Open the field log', 'Read the quest book entry, check the first-join message, and get oriented before leaving the clearing.')],
        [stack('minecraft:bread', 4)]),
      quest('clearing-kit', 'Inventory Audit',
        'The starting gear covers light, water, mapping, woodcutting, and food work. Account for every tool before moving.',
        -100, 0, 'omegaflashlight:flashlight',
        [detectTask('Carry the issued kit', ['omegaflashlight:flashlight', ['legendarysurvivaloverhaul:purified_water_bottle', 2], 'antiqueatlas:empty_antique_atlas', 'minecraft:stone_axe', 'butchery:bone_cleaver'], 'Have the flashlight, two purified water bottles, the empty atlas, the stone axe, and the bone cleaver in your inventory.')],
        [stack('hardcorequesting:quarterheart')], ['clearing-wake']),
      quest('clearing-wood', 'Timber For A Door',
        'FallingTree makes timber work quick. Gather enough wood for walls, storage, and repairs before the light thins out.',
        -60, 0, 'minecraft:oak_log',
        [detectTask('Stockpile logs', [['minecraft:oak_log', 24, 'TAG_FUZZY']], 'Carry at least twenty-four logs. Any local timber is acceptable; the point is enough material for a sealed room.')],
        [stack('minecraft:torch', 8)], ['clearing-kit']),
      quest('clearing-stone', 'Stone And Coal',
        'Stone tools, a furnace, and spare coal make the first camp practical. Gather them before settling in for the evening.',
        -20, 0, 'minecraft:cobblestone',
        [detectTask('Gather base stone', [['minecraft:cobblestone', 32, 'TAG_FUZZY'], ['minecraft:coal', 8, 'TAG_FUZZY']], 'Carry building stone and fuel. Do not spend the first dusk mining with an open back.')],
        [stack('minecraft:glass', 8)], ['clearing-wood']),
      quest('clearing-shelter', 'A Door Between You And It',
        'Build a small room that closes. It does not need to be scenic; it needs to keep supplies dry and give you a controlled doorway.',
        20, 0, 'minecraft:oak_door',
        [manualTask('Seal the first room', 'Build a fully enclosed shelter with a door, a light source, a chest, and line of sight to the outside. Mark this only after you can shut yourself in and still find your supplies.')],
        [stack('minecraft:charcoal', 8)], ['clearing-stone']),
      quest('clearing-bed', 'Morning Check',
        'A rested start makes fieldwork safer. Set a respawn point and keep track of where you wake.',
        60, 0, 'minecraft:red_bed',
        [detectTask('Set a respawn point', ['minecraft:red_bed'], 'Carry or place a bed. If you use a bedroll instead, keep this as a manual checkpoint and mark it after your spawn point is secured.')],
        [stack('minecraft:white_wool', 4)], ['clearing-shelter']),
      quest('clearing-atlas', 'Name The Clearing',
        'F3 is restricted, so the Antique Atlas is your route record. Start with names you can remember under bad weather.',
        100, 0, 'antiqueatlas:empty_antique_atlas',
        [detectTask('Keep the atlas', ['antiqueatlas:empty_antique_atlas'], 'Keep the atlas on you until you can convert it into a marked field map.')],
        [stack('minecraft:paper', 12)], ['clearing-bed']),
      quest('clearing-backpack', 'Field Pack Space',
        'A backpack gives you room for water, bandages, batteries, food, spare blocks, and samples from the day.',
        140, 0, 'backpacked:backpack',
        [craftTask('Craft a backpack', ['backpacked:backpack'])],
        [stack('minecraft:leather', 4)], ['clearing-atlas']),
      quest('clearing-night', 'Nightfall Routine',
        'Dense woods feel different after sundown. Stay close to camp and learn how far your light reaches.',
        20, 70, 'minecraft:clock',
        [manualTask('Stay through one full night', 'Stay alive from nightfall to dawn in the Overworld. Use walls, light, sound, and retreat routes. Do not wander just because the path still looks familiar.')],
        [stack('hardcorequesting:quarterheart')], ['clearing-shelter']),
      quest('clearing-hostiles', 'Known Hostiles',
        'Clear common hostiles around camp so routine night work is less chaotic.',
        60, 70, 'minecraft:iron_sword',
        [killTask('Put down zombies', 'minecraft:zombie', 5), killTask('Break skeleton line of fire', 'minecraft:skeleton', 3)],
        [stack('minecraft:arrow', 16)], ['clearing-night']),
      quest('clearing-routine', 'The First Routine',
        'A camp works when supplies, exits, light, and habits are repeatable.',
        100, 70, 'minecraft:campfire',
        [manualTask('Stabilize the clearing', 'Before opening the rest of the book, have a sealed shelter, spare food, drinkable water, torches or lamps, a marked atlas, storage, and a route you can run in the dark.')],
        [stack('hardcorequesting:halfheart')], ['clearing-hostiles', 'clearing-backpack'])
    ]
  },
  {
    file: 'light_and_climate',
    name: 'Light, Thirst, Temperature',
    description: 'Clean water, reliable light, medicine, and temperature control turn a clearing into a working camp.',
    quests: [
      quest('light-water', 'Boil The Creek',
        'Thirsty Bottles and Legendary Survival make untreated water a liability. Boil it before longer walks.',
        -120, 0, 'legendarysurvivaloverhaul:purified_water_bottle',
        [craftTask('Make purified water', ['legendarysurvivaloverhaul:purified_water_bottle'], 'Use the custom campfire cooking recipe to turn water bottles into purified water.')],
        [stack('minecraft:charcoal', 8)], ['clearing-routine']),
      quest('light-canteen', 'Capped Water',
        'Loose bottles are a short walk. A canteen is a patrol.',
        -80, 0, 'legendarysurvivaloverhaul:canteen',
        [craftTask('Craft a canteen', ['legendarysurvivaloverhaul:canteen'])],
        [stack('legendarysurvivaloverhaul:purified_water_bottle', 2)], ['light-water']),
      quest('light-bandage', 'Red Means Stop',
        'Field injuries are easier to handle when the supplies are already packed.',
        -40, 0, 'legendarysurvivaloverhaul:bandage',
        [craftTask('Craft bandages', [['legendarysurvivaloverhaul:bandage', 3]])],
        [stack('minecraft:string', 8)], ['light-canteen']),
      quest('light-medicine', 'Field Dressing',
        'Longer trips need more than cloth. Stock a simple medical shelf before deeper routes.',
        0, 0, 'legendarysurvivaloverhaul:first_aid_supplies',
        [craftTask('Craft first aid supplies', ['legendarysurvivaloverhaul:first_aid_supplies'])],
        [stack('legendarysurvivaloverhaul:healing_herbs', 2)], ['light-bandage']),
      quest('light-thermometer', 'Read The Air',
        'Cold Sweat, Serene Seasons, snow behavior, and survival temperature mean weather needs to be measured, not guessed.',
        40, 0, 'legendarysurvivaloverhaul:thermometer',
        [craftTask('Craft a thermometer', ['legendarysurvivaloverhaul:thermometer'])],
        [stack('minecraft:redstone', 8)], ['light-medicine']),
      quest('light-calendar', 'Season Notes',
        'The calendar explains what changed: crops, cold, daylight, and how long the return walk feels.',
        80, 0, 'legendarysurvivaloverhaul:seasonal_calendar',
        [craftTask('Craft a seasonal calendar', ['legendarysurvivaloverhaul:seasonal_calendar'])],
        [stack('minecraft:paper', 8)], ['light-thermometer']),
      quest('light-boiler', 'A Warm Room',
        'The heater recipe is deliberately heavier. Permanent heat makes winter and altitude manageable.',
        120, 0, 'legendarysurvivaloverhaul:heater',
        [craftTask('Craft a heater', ['legendarysurvivaloverhaul:heater'])],
        [stack('minecraft:coal_block')], ['light-calendar']),
      quest('light-battery', 'Reserve Power',
        'The flashlight is useful only while it has charge. Spare batteries decide how far you can work from camp.',
        -80, 70, 'omegaflashlight:medium_battery',
        [craftTask('Craft spare batteries', ['omegaflashlight:small_battery', 'omegaflashlight:medium_battery'])],
        [stack('minecraft:redstone', 12)], ['clearing-kit']),
      quest('light-fixed', 'Fixed Light',
        'Handheld light saves the moment. Fixed light changes the map.',
        -40, 70, 'omegaflashlight:basic_lamp',
        [craftTask('Craft a basic lamp', ['omegaflashlight:basic_lamp'])],
        [stack('minecraft:glowstone_dust', 8)], ['light-battery']),
      quest('light-coded', 'Color Code The Perimeter',
        'The pack includes custom colorful-lighting compatibility. Use color like an emergency language: red danger, blue water, green exit.',
        0, 70, 'omegaflashlight:dye_table',
        [craftTask('Craft the dye table', ['omegaflashlight:dye_table'])],
        [stack('minecraft:red_dye', 4), stack('minecraft:blue_dye', 4)], ['light-fixed']),
      quest('light-upgrade', 'A Beam You Trust',
        'A high-quality lamp is not luxury. It makes routine work easier when fog or rain cuts visibility.',
        40, 70, 'omegaflashlight:high_quality_lamp',
        [craftTask('Craft a high-quality lamp', ['omegaflashlight:high_quality_lamp'])],
        [stack('hardcorequesting:quarterheart')], ['light-coded']),
      quest('light-blackout', 'Blackout Drill',
        'Wind, rain, bad placement, or a missed marker can make the return route darker than expected.',
        80, 70, 'minecraft:redstone_torch',
        [manualTask('Run a no-torch retreat', 'From a marked point outside camp, return using only the atlas, one handheld light, and permanent landmarks. Do this before trusting any cave route.')],
        [stack('minecraft:glow_ink_sac', 4)], ['light-upgrade'])
    ]
  },
  {
    file: 'food_and_butchery',
    name: 'Food And Butchery',
    description: 'Food progression is practical fieldwork: forage, hunt, process cleanly, cook properly, and keep stores organized.',
    quests: [
      quest('food-forage', 'Calories Before Courage',
        'Every patrol starts with food. Hunger makes bad navigation worse.',
        -200, 0, 'minecraft:sweet_berries',
        [detectTask('Carry field food', [['minecraft:bread', 8, 'TAG_FUZZY']], 'Carry at least eight pieces of reliable food. Substitute another staple manually if your world start provides it.')],
        [stack('minecraft:apple', 4)], ['clearing-routine']),
      quest('food-cleaver', 'Issued Cleaver',
        'The bone cleaver in the kit belongs to food work. Keep it with the rest of the camp tools.',
        -160, 0, 'butchery:bone_cleaver',
        [detectTask('Carry the cleaver', ['butchery:bone_cleaver'])],
        [stack('minecraft:bone', 8)], ['food-forage']),
      quest('food-knife', 'Skinning Knife',
        'Use the correct tool. Bad work wastes food and leaves evidence around the base.',
        -120, 0, 'butchery:bone_skinning_knife',
        [craftTask('Craft a skinning knife', ['butchery:bone_skinning_knife'])],
        [stack('minecraft:leather', 3)], ['food-cleaver']),
      quest('food-table', 'Table Work',
        'Move carcass processing away from beds, maps, and drinking water. Clean stations keep the camp usable.',
        -80, 0, 'butchery:oak_butchers_table',
        [craftTask('Craft a butcher table', ['butchery:oak_butchers_table'])],
        [stack('minecraft:iron_nugget', 16)], ['food-knife']),
      quest('food-hunt', 'Clean Kill',
        'Hunt normal animals for food, not trophies. The goal is a stocked larder and a clean work area.',
        -40, 0, 'minecraft:beef',
        [killTask('Hunt cattle', 'minecraft:cow', 2), killTask('Hunt pigs', 'minecraft:pig', 2)],
        [stack('minecraft:coal', 8)], ['food-table']),
      quest('food-render', 'Render The Scraps',
        'Butchery adds fat, bones, organs, and other byproducts. Learn what can be stored and what should stay outside.',
        0, 0, 'butchery:animal_fat',
        [detectTask('Recover animal fat', ['butchery:animal_fat'], 'Process carcasses until you recover animal fat. This makes the butchery loop explicit without forcing a specific animal variant.')],
        [stack('minecraft:bowl', 8)], ['food-hunt']),
      quest('food-pot', 'A Real Meal',
        'The custom cooking pot recipe marks the shift from eating to planning.',
        40, 0, 'farmersdelight:cooking_pot',
        [craftTask('Craft a cooking pot', ['farmersdelight:cooking_pot'])],
        [stack('minecraft:brick', 8)], ['food-render']),
      quest('food-stove', 'Permanent Kitchen',
        'A stove is base infrastructure. Meals become checklists: water, protein, vegetables, warmth, time.',
        80, 0, 'farmersdelight:stove',
        [craftTask('Craft a stove', ['farmersdelight:stove'])],
        [stack('minecraft:magma_block')], ['food-pot']),
      quest('food-storage', 'Labeled Stores',
        'Crates keep the base readable when something is outside and you have ten seconds to leave.',
        120, 0, 'farmersdelight:carrot_crate',
        [craftTask('Craft a food crate', ['farmersdelight:carrot_crate'])],
        [stack('minecraft:chest', 2)], ['food-stove']),
      quest('food-heart-fragment', 'Red Glass And Herbs',
        'The custom heart progression makes medicine a long-term project instead of a quick reset.',
        160, 0, 'legendarysurvivaloverhaul:heart_fragment',
        [craftTask('Craft a heart fragment', ['legendarysurvivaloverhaul:heart_fragment'])],
        [stack('minecraft:red_stained_glass', 4)], ['food-storage']),
      quest('food-heart', 'Crystal Heart',
        'Spend the gold apple when the camp can afford it. Extra health is a buffer for bad weather, bad footing, and bad decisions.',
        200, 0, 'legendarysurvivaloverhaul:heart_container',
        [craftTask('Craft a heart container', ['legendarysurvivaloverhaul:heart_container'])],
        [stack('hardcorequesting:halfheart')], ['food-heart-fragment'])
    ]
  },
  {
    file: 'exploration_and_evidence',
    name: 'Exploration And Evidence',
    description: 'Map the forest like a survey grid. Photograph landmarks, keep notes, and make every return route easier than the first trip.',
    quests: [
      quest('explore-map', 'Perimeter Map',
        'Mark water, shelter, caves, campsites, bunkers, and places where the terrain changes. The atlas is your field memory.',
        -100, 0, 'antiqueatlas:empty_antique_atlas',
        [manualTask('Mark five locations', 'Add at least five atlas markers: base, water, cave, campsite, bunker, redwood landmark, or suspicious structure.')],
        [stack('minecraft:paper', 12)], ['clearing-routine']),
      quest('explore-campsite', 'Empty Campsite',
        'Campsites, bunkers, and abandoned shelters are useful landmarks. Check them carefully before calling them clear.',
        -60, 0, 'minecraft:lantern',
        [manualTask('Sweep a campsite or bunker', 'Find and clear a campsite, abandoned shelter, or underground bunker. Mark it before looting so you can find it again if the forest changes the route.')],
        [stack('minecraft:torch', 12)], ['explore-map']),
      quest('explore-camera', 'Camera Before Memory',
        'Exposure turns field notes into evidence. Build the camera before relying on memory alone.',
        -20, 0, 'exposure:camera',
        [craftTask('Craft a camera', ['exposure:camera'])],
        [stack('minecraft:glass_pane', 8)], ['explore-campsite']),
      quest('explore-film', 'Load Film',
        'A camera without film is just weight. Bring records, not stories.',
        20, 0, 'exposure:black_and_white_film',
        [craftTask('Craft black-and-white film', ['exposure:black_and_white_film'])],
        [stack('minecraft:paper', 8)], ['explore-camera']),
      quest('explore-photo', 'Photograph A Landmark',
        'Take a picture of a place that would be hard to describe twice.',
        60, 0, 'exposure:photograph',
        [manualTask('Take one field photo', 'Photograph a structure, cave entrance, unusual sign, trail marker, old camp, or light source. HQM cannot inspect photo contents, so this is manual by design.')],
        [stack('hardcorequesting:quarterheart')], ['explore-film']),
      quest('explore-album', 'Case File',
        'Loose photos get lost. An album becomes a record.',
        100, 0, 'exposure:album',
        [craftTask('Craft a photo album', ['exposure:album'])],
        [stack('minecraft:ink_sac', 4)], ['explore-photo']),
      quest('explore-geode', 'Stone With Teeth',
        'Spelunker\'s Charm makes caves more varied than simple tunnels. Bring back one clean specimen.',
        -100, 70, 'spelunkers_charm:geode',
        [detectTask('Recover a geode', ['spelunkers_charm:geode'])],
        [stack('minecraft:iron_ingot', 4)], ['explore-campsite']),
      quest('explore-helmet', 'Light On Your Head',
        'Hands-free light is survival equipment when the other hand needs blocks, a weapon, or a radio.',
        -60, 70, 'spelunkers_charm:candle_helmet',
        [craftTask('Craft a candle helmet', ['spelunkers_charm:candle_helmet'])],
        [stack('minecraft:candle', 8)], ['explore-geode']),
      quest('explore-cave-run', 'Below The Roots',
        'Caves are closed work sites with dust, echoes, poor sightlines, and awkward exits.',
        -20, 70, 'minecraft:deepslate',
        [manualTask('Complete a cave run', 'Enter a cave below Y 40, collect ore or a geode, mark the entrance, and return to base with light, water, and one exit route still intact.')],
        [stack('minecraft:iron_ingot', 6)], ['explore-helmet', 'light-blackout']),
      quest('explore-nature', 'Specimen Jar',
        'Wildlife makes the forest easier to read. Catalog small signs of life before assuming an area is empty.',
        20, 70, 'alexsmobs:banana_slug_slime',
        [detectTask('Collect a forest specimen', ['alexsmobs:banana_slug_slime'])],
        [stack('minecraft:slime_ball', 2)], ['explore-map']),
      quest('explore-old-recording', 'Old Recording',
        'The pack includes recording, voice, radio, ambience, and sound-physics systems. If a sound has direction, it is worth noting.',
        60, 70, 'minecraft:music_disc_11',
        [manualTask('Investigate an unusual sound', 'When you hear a knock, footstep, voice, mining sound, radio hit, or cave noise that does not match a visible source, stop and write down location, time, weather, and light level.')],
        [stack('minecraft:note_block', 2)], ['explore-album']),
      quest('explore-return', 'Return With Proof',
        'A successful expedition ends at the table, not at the loot chest.',
        100, 70, 'minecraft:writable_book',
        [manualTask('File the first field report', 'Return to base with a marked atlas, at least one photo or written note, one sample, and a supply list for the next trip.')],
        [stack('hardcorequesting:halfheart')], ['explore-cave-run', 'explore-old-recording'])
    ]
  },
  {
    file: 'field_procedures',
    name: 'Field Procedures',
    description: 'This chapter is ordinary field discipline: patrol routes, notes, shelter checks, sound logs, cave procedure, and returning on schedule.',
    quests: [
      quest('encounter-eyes', 'Tree Line Watch',
        'Watch the same edge of the forest long enough to learn what belongs there.',
        -80, 0, 'minecraft:spyglass',
        [manualTask('Keep a watch', 'Spend one night cycle observing the tree line from shelter or a marked blind. Record weather, moonlight, sound changes, and anything that seems out of place.')],
        [stack('minecraft:glow_ink_sac', 4)], ['clearing-night']),
      quest('encounter-paranormal', 'Sleep Log',
        'A simple morning log catches details that fatigue can blur.',
        -40, 0, 'minecraft:phantom_membrane',
        [manualTask('Record three mornings', 'For three mornings, log bed location, base damage, missing lights, unusual sounds, and whether the route outside still matches your atlas.')],
        [stack('minecraft:string', 12)], ['encounter-eyes']),
      quest('encounter-serverhorror', 'False Records',
        'Field records are useful because memory edits itself after a long night.',
        0, 0, 'minecraft:oak_sign',
        [manualTask('Log an inconsistency', 'Record one thing that does not fit: a sign you forgot placing, a sound without a clear source, a light that changed, a route that feels shorter, or damage without an obvious cause.')],
        [stack('minecraft:paper', 12)], ['encounter-paranormal']),
      quest('encounter-anomaly', 'Pattern Notes',
        'A single odd detail is a note. Three odd details in the same place are a pattern.',
        40, 0, 'minecraft:writable_book',
        [manualTask('Start a pattern log', 'Choose one marked location and revisit it at least three times: day, dusk, and night. Record light level, sounds, movement, weather, and what changed between visits.')],
        [stack('minecraft:amethyst_shard', 4)], ['encounter-serverhorror']),
      quest('encounter-stalker', 'Sound Survey',
        'Sound carries differently under trees. Direction is useful, but hills, caves, and rain can bend it.',
        80, 0, 'minecraft:sculk_sensor',
        [manualTask('Map the soundscape', 'At three atlas markers, stop moving for thirty seconds and write down what you hear. Mark any sound that repeats from an unexpected direction.')],
        [stack('minecraft:arrow', 16)], ['encounter-anomaly']),
      quest('encounter-cavedweller', 'Low-Ceiling Route',
        'Caves are work sites. The objective is a route you can leave even when visibility is poor.',
        -120, 70, 'minecraft:deepslate',
        [manualTask('Mark an underground route', 'Below Y 40, mark an entrance, place three return markers, collect one useful resource, and exit without digging straight up or abandoning your path.')],
        [stack('hardcorequesting:quarterheart')], ['explore-cave-run', 'encounter-stalker']),
      quest('encounter-palehound', 'Open-Ground Route',
        'Open ground is easy to cross until weather, hunger, or poor light changes the pace.',
        -80, 70, 'minecraft:grass_block',
        [manualTask('Cross and return', 'Travel from base to an open landmark and back with food, water, a marked detour, and enough blocks to make temporary cover.')],
        [stack('hardcorequesting:quarterheart')], ['encounter-stalker']),
      quest('encounter-goatman', 'Vertical Escape',
        'A single door is a bottleneck. Build exits that work even when the front of camp is blocked.',
        -40, 70, 'minecraft:ladder',
        [manualTask('Build a second exit', 'Add a roof hatch, ladder shaft, rear door, bridge, or drop route to your base. Test it once at night with your normal field kit.')],
        [stack('hardcorequesting:halfheart')], ['encounter-palehound', 'light-upgrade']),
      quest('encounter-knocker', 'Door Drill',
        'A door is a delay, not a whole plan. Practice moving through camp without using the front entrance.',
        0, 70, 'minecraft:iron_door',
        [manualTask('Run a breach drill', 'From inside the base, rehearse leaving through the backup route, grabbing the go-bag, and reaching the nearest atlas marker without opening the front door.')],
        [stack('minecraft:iron_door')], ['encounter-stalker']),
      quest('encounter-masked', 'Messy Camp',
        'Some campsites are messy enough to deserve notes before loot.',
        40, 70, 'minecraft:bone_block',
        [manualTask('Secure a scene', 'Find a camp, shelter, trail, or room that feels out of place. Photograph it, mark it, check the perimeter, and only then remove supplies.')],
        [stack('minecraft:bone_block', 2)], ['explore-album', 'encounter-knocker']),
      quest('encounter-corpse-cleaner', 'Clean Tools',
        'Cleanup is procedure. If you cannot tell what changed, your next notes will be worse.',
        80, 70, 'minecraft:bucket',
        [detectTask('Carry cleanup supplies', ['minecraft:bucket', 'minecraft:shovel', 'minecraft:torch'], 'Carry basic cleanup and marking supplies: bucket, shovel, and torch.')],
        [stack('minecraft:iron_ingot', 4)], ['encounter-masked']),
      quest('encounter-containment', 'Evidence Board',
        'Stop treating odd notes as separate scraps. Put them where they can be compared: time, light, biome, sound, route, damage, evidence.',
        120, 70, 'exposure:album',
        [manualTask('Build the evidence board', 'At base, organize at least three notes or photos: one night log, one cave route, and one structure or campsite record. Mark routes and countermeasures beside each.')],
        [stack('hardcorequesting:heart')], ['encounter-cavedweller', 'encounter-goatman', 'encounter-corpse-cleaner'])
    ]
  },
  {
    file: 'signals_and_escalation',
    name: 'Signals And Escalation',
    description: 'Once the base is stable, the book moves into communication, range checks, practice, and a controlled overnight watch.',
    quests: [
      quest('signal-wire', 'Copper Voice',
        'Simple Radio starts with parts. Make wire before pretending anyone can hear you.',
        -140, 0, 'simpleradio:copper_wire',
        [craftTask('Craft copper wire', ['simpleradio:copper_wire'])],
        [stack('minecraft:copper_ingot', 4)], ['explore-return']),
      quest('signal-walkie', 'Short Range',
        'A handheld radio is useful in multiplayer and still a good habit in single player. Test the tool before needing it.',
        -100, 0, 'simpleradio:walkie_talkie',
        [craftTask('Craft a walkie talkie', ['simpleradio:walkie_talkie'])],
        [stack('minecraft:redstone', 8)], ['signal-wire']),
      quest('signal-station', 'Base Station',
        'A station turns the shelter into an outpost and keeps reports centered in one place.',
        -60, 0, 'simpleradio:radio',
        [craftTask('Craft radio hardware', ['simpleradio:radio', 'simpleradio:antenna'])],
        [stack('minecraft:iron_ingot', 6)], ['signal-walkie']),
      quest('signal-tools', 'Tune The Signal',
        'The Radiosmithing Station and Frequencer make contact deliberate. Record every frequency that carries clearly.',
        -20, 0, 'simpleradio:radiosmither',
        [craftTask('Craft radio tools', ['simpleradio:radiosmither', 'simpleradio:frequencer'])],
        [stack('minecraft:gold_ingot', 2)], ['signal-station']),
      quest('signal-transceiver', 'Two-Way Contact',
        'A transceiver is the first serious attempt to push a signal past rough terrain.',
        20, 0, 'simpleradio:transceiver',
        [craftTask('Craft a transceiver', ['simpleradio:transceiver'])],
        [stack('hardcorequesting:quarterheart')], ['signal-tools']),
      quest('signal-backup', 'Backup Channel',
        'The separate Walkie-Talkie mod gives a simpler fallback. Redundancy is useful when weather or distance cuts the first channel.',
        -100, 70, 'walkietalkie:iron_walkietalkie',
        [craftTask('Craft an iron walkie-talkie', ['walkietalkie:iron_walkietalkie'])],
        [stack('minecraft:iron_ingot', 4)], ['signal-walkie']),
      quest('signal-range', 'Range Test',
        'Test contact from the edge of the marked perimeter. The return trip is part of the route check.',
        60, 0, 'minecraft:repeater',
        [manualTask('Transmit from a marked point', 'Walk to a marked atlas point outside the base, test the radio setup, record whether anything answers, and return before nightfall.')],
        [stack('minecraft:redstone_torch', 4)], ['signal-transceiver']),
      quest('signal-bench', 'Escalation Bench',
        'TaCZ belongs late in the field plan. Build the workbench before wasting ammunition during a real emergency.',
        -60, 70, 'tacz:workbench_a',
        [craftTask('Craft a gun workbench', [['tacz:workbench_a', 1, 'NBT_FUZZY']])],
        [stack('minecraft:gunpowder', 8)], ['explore-cave-run']),
      quest('signal-target', 'Do Not Learn While Chased',
        'Practice before bringing firearms into a cave, campsite, or night route.',
        -20, 70, 'tacz:target',
        [craftTask('Craft a target', ['tacz:target'])],
        [stack('minecraft:paper', 8)], ['signal-bench']),
      quest('signal-ammo', 'Count Every Round',
        'A gun without discipline makes louder mistakes.',
        20, 70, 'minecraft:gunpowder',
        [consumeTask('Stock holdout supplies', [['minecraft:gunpowder', 16], ['minecraft:iron_ingot', 8], ['minecraft:paper', 8]], 'Submit basic ammunition materials to prove you can spare them. The reward is small because preparation is the real reward.')],
        [stack('minecraft:flint', 8)], ['signal-target']),
      quest('signal-holdout', 'Holdout Night',
        'End the first major arc by staffing the outpost overnight without breaking procedure.',
        100, 0, 'minecraft:crossbow',
        [manualTask('Survive a controlled holdout', 'Spend a full night at the outpost with stocked water, food, light, medical supplies, radio access, a weapon, escape route, and an evidence log. Do not sleep through it.')],
        [stack('hardcorequesting:heart')], ['signal-range', 'signal-ammo', 'encounter-containment']),
      quest('signal-final-report', 'Transmit The Report',
        'Reports are only useful when sent. Transmit before the day\'s details blur together.',
        140, 0, 'simpleradio:transceiver',
        [manualTask('Send the case summary', 'At dawn after the holdout, transmit a summary: base status, missing routes, weather, injuries if any, changed landmarks, and whether the tree line moved.')],
        [stack('hardcorequesting:heart')], ['signal-holdout'])
    ]
  },
  {
    file: 'boundary_notes',
    name: 'Boundary Notes',
    description: 'Boundary work is simple: mark the edge of the useful map, test uncertain routes, and come back with notes.',
    quests: [
      quest('wrong-limbo-note', 'Old Route Note',
        'Some older field notes mention routes that do not appear on the current map. Treat them as unreliable until the ground proves otherwise.',
        -120, 0, 'minecraft:ender_eye',
        [manualTask('Check an old route', 'Choose one suspicious path, cave mouth, ravine, bunker stairwell, or broken road. Mark the entrance, walk no farther than you can safely return, and record whether the route matches the terrain around it.')],
        [stack('minecraft:ender_pearl', 2)], ['explore-cave-run']),
      quest('wrong-limbo-enter', 'Unmarked Turn',
        'A bad route is useful once it is named. Unknown ground stops being confusing when it becomes a warning marker.',
        -80, 0, 'minecraft:compass',
        [manualTask('Mark the uncertain turn', 'Place an atlas marker and a physical marker at a route that disorients you, loops strangely, drops too sharply, or changes visibility faster than the surrounding forest.')],
        [stack('hardcorequesting:quarterheart')], ['wrong-limbo-note']),
      quest('wrong-void-note', 'Bad Ground',
        'Low places collect water, fog, debris, and bad footing. Survey them before the next expedition depends on crossing them.',
        -40, 0, 'minecraft:echo_shard',
        [manualTask('Survey a low place', 'Find a sinkhole, deep cave, flooded trench, ravine, or basin. Mark safe footing, unsafe footing, water access, and the fastest return path.')],
        [stack('minecraft:amethyst_shard', 4)], ['wrong-limbo-note']),
      quest('wrong-void-enter', 'Below The Sound',
        'The deepest trips are not only for loot. They test whether your route markers are clear enough to follow tired.',
        0, 0, 'minecraft:sculk',
        [manualTask('Run a depth test', 'Descend to the lowest safe point on a marked route, pause for thirty seconds, then return without taking a new tunnel home.')],
        [stack('hardcorequesting:quarterheart')], ['wrong-void-note']),
      quest('wrong-recipe', 'Pocket Notes',
        'If you cannot explain a route yet, at least make the note legible for the next person using your map.',
        40, 0, 'minecraft:writable_book',
        [manualTask('Write a route warning', 'Write a short note for one dangerous location: what it looks like, why it is unsafe, what supplies are required, and when to turn back.')],
        [stack('minecraft:paper', 8)], ['wrong-void-note']),
      quest('wrong-return', 'Find A Way Out',
        'The only successful boundary survey is the one that ends back at camp.',
        80, 0, 'minecraft:recovery_compass',
        [manualTask('Return alive', 'Return to base from a marked boundary, low place, or uncertain turn with your quest book, atlas, light, and one useful note or photograph.')],
        [stack('hardcorequesting:halfheart')], ['wrong-limbo-note', 'wrong-void-note']),
      quest('wrong-report', 'File The Boundary',
        'Unclear routes still need procedure: map them, photograph them, transmit them, and do not rely on memory.',
        120, 0, 'exposure:album',
        [manualTask('Document the boundary case', 'Add a photo or written note about the route, mark it on the atlas, and transmit the status from the radio station.')],
        [stack('hardcorequesting:heart')], ['wrong-return', 'signal-transceiver'])
    ]
  }
];

mkdirSync(setsDir, { recursive: true });
if (existsSync(setsDir)) {
  for (const file of readdirSync(setsDir)) {
    if (file.endsWith('.json')) unlinkSync(join(setsDir, file));
  }
}

writeFileSync(
  join(outDir, 'description.txt'),
  [
    'The Forest is a field survival guide about building a camp, mapping routes, and returning safely from the trees.',
    'Every chapter favors procedure, evidence, light discipline, and careful retreat.'
  ].join('\n') + '\n'
);
writeFileSync(join(outDir, 'sets.json'), JSON.stringify({ sets: sets.map(set => set.file) }, null, 2) + '\n');
writeFileSync(join(outDir, 'bags.json'), '[]\n');
writeFileSync(join(outDir, 'reputations.json'), '[]\n');

for (const set of sets) {
  writeFileSync(join(setsDir, `${set.file}.json`), JSON.stringify({
    name: set.name,
    description: wt(set.description),
    quests: set.quests,
    reputationBar: []
  }, null, 2) + '\n');
}
