#Indigo properties file
<<<<<<< Updated upstream
#Tue Jul 07 20:01:50 AEST 2026
always-tesselate-blocks=auto
ambient-occlusion-mode=hybrid
=======
#Thu Jul 09 17:14:01 AEST 2026
fix-mean-light-calculation=auto
>>>>>>> Stashed changes
debug-compare-lighting=auto
fix-exterior-vertex-lighting=auto
fix-luminous-block-ambient-occlusion=auto
fix-mean-light-calculation=auto
fix-smooth-lighting-offset=auto
