#KubeJS Dev Properties
#Mon Jul 06 12:12:50 AEST 2026
alwaysCaptureErrors=false
dataPackOutput=false
debugInfo=false
logAddedRecipes=false
logErroringRecipes=true
logGeneratedData=false
logInvalidRecipeHandlers=true
logModifiedRecipes=false
logRemovedRecipes=false
logSkippedPlugins=true
logSkippedRecipes=false
logSkippedTags=false
strictTags=false
